# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScoringSystemAdmin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Swifter', '~> 1.5.0'
  pod 'Firebase', '>= 2.5.0'
  pod 'Firebase/Firestore'
  # Pods for ScoringSystemAdmin

  target 'ScoringSystemAdminTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScoringSystemAdminUITests' do
    # Pods for testing
  end

end
